// This file was autogenerated by D:\Work\GitHub\blogger.relatedposts\lib\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/blogger/relatedposts/main.js', ['garafu.blogger.relatedposts.Main'], ['garafu.blogger.relatedposts.Settings', 'garafu.dom', 'garafu.events']);
goog.addDependency('../../../../src/blogger/relatedposts/settings.js', ['garafu.blogger.relatedposts.Settings'], []);
goog.addDependency('../../../../src/dom/dom.js', ['garafu.dom'], []);
goog.addDependency('../../../../src/events/events.js', ['garafu.events'], []);
